### ISSUE TITLE
How would I integrate the mongoose 'Population' feature?

### ISSUE THREAD

**Issue by biofractal** [travist/resourcejs#1]
Thanks for writing resourcejs, I am having a play around and so far have enjoyed its ease of use.

I was wondering how I would make use of the mongoose `Populate()` feature to create post-hoc joins? I have the following simple, test model.

```
product = new Schema
	name	: String
	price		: Number

house = new Schema
	client		: String
	products	: [{ type: Schema.ObjectId, ref: 'product' }]
```

This is working just fine however, as you would expect, the `house.products` array is returning a list of naked objectIds whereas I would like this get this list populated with the actual product. 

Looking through your examples I can see you support nested models, which is great and I suspect that I must need to use a before handler in a similar fashion but I am not sure how to go about this.

Can you show my me how I would `mongoose.populate` my model using resourcejs please?

Thanks

**Comment by travist** [comment]
You should be able to use the same mechanism that I used in the nested resources to filter based on the parent ID, but include the populate command along with the filter.  Like so.

```
// The child REST interface.
Resource(app, '/parent/:parentId', 'child', Child).rest({

  // Add a before handler to include filter and parent information.
  before: function(req, res, next) {
    req.body.parent = req.params.parentId;
    req.modelQuery = this.model.where('parent', req.params.parentId).populate('parent');
    next();
  }
});
```
I have not actually tried this, so let me know if it does not work.

**Comment by biofractal** [comment]
Hi

OK, so I have the population stuff working. 

To clarify, I want to simply populate the `house` document's inner `products` array with the equivalent `product` documents. Here is how I did it.

```
schema: new Schema
	client		: String
	products	: [{ type: Schema.ObjectId, ref: 'product' }]

options:
	before:(req, res, next)->
		req.modelQuery = @model.where().populate 'products'
		next()
```

It seems that I do not need to pass anything into the where clause, presumably you are somehow chaining the custom `modelQuery` onto the original query. 

This technique works but it has raised a couple of additional questions:

1. When fetching the complete list of `house` resources I don't want to populate the products array but instead just return the simple array of ids. How would I constrain the before handle to only work with GET single item and not the complete list? FYI: I had some clunky code in the `before` handler that checked to see if an id was being passed through on the query.params but I was wondering if there was a better way?

2. I tried to constrain the handler to only work on GETs, like this:

```
options:
	beforeGet:(req, res, next)->
		console.log 'called'
		req.modelQuery = @model.where().populate 'products'
		next()
```

but when I do this the `beforeGet` handler fails to get called regardless. Can you spot what I am doing wrong here?

Thanks for your help.

**Comment by biofractal** [comment]
In fact the `beforeGet` does work as advertised :-) Sorry about that. So just in case anybody is following along, here is how to populate single items whilst not populating the list of items.

options:
	beforeIndex:(req, res, next)->
		console.log 'just returning the index list, no action required'
		next()

	beforeGet:(req, res, next)->
		req.modelQuery = @model.where().populate 'products'
		next()
