### ISSUE TITLE
Can we add support for virtual resources?

### ISSUE THREAD

**Issue by biofractal** [travist/resourcejs#11]
Resourcejs does not currently support the concept of a REST 'virtual resource', that is a resource that is not represented by mongodb document and therefore is not defined by a mongoose schema.

Given the original aims of resourcejs to provide CRUD access to mongodb domain documents, this is a perfectly reasonable constraint, however it seems to me to be a vital omission if resourcejs is to be used (as I am using it) as a REST API generator that  services and extends a mongodb domain. For example I have used resourcejs to enhance mongodb with field level encryption and sliding expiration TTL fields.

Therefore, do you agree that adding the ability to generate endpoints for schema-less, virtual resources is a worthwhile enhancement and if so do you have any ideas how we might go about implementing this? I am happy to do the work but I would greatly appreciate your design input.

Thanks

**Comment by travist** [comment]
I am 100% on board with this approach and can envision an architecture that would facilitate this. I believe what we need are a few abstraction classes that would expose the "model" interface and then create classes that extend this interface. One of those classes would be the Mongoose model class, while the other would simply provide either in-memory manipulation or "virtual" restful capabilities.

Great idea and I am very supportive of your development of that feature.

Thanks for your help.

Travis.

**Comment by biofractal** [comment]
I now have a working solution that I would like to run by you. Its solves my specific use-case and seems to be generally useful as a means of presenting virtual resources.

I have added a new pseudo-method, along the lines of 'index', called 'virtual'. One or more of the virtual methods can be for a given concrete resource and are described in the usual way, by passing options to the resource.virtual method or otherwise as described for the other methods (index, get etc).

The virtual method further expects a virtual-resource name and a before function to be provided via its options. The function acts on the concrete resource and returns virtual resource of arbitrary shape. For example, the before function could be a mongo aggregate function that acts on the resource to return an arbitrary result. The name is used to specify the url according to the format:

/[resource-name]/virtual/[virtual-resource-name]

for example, given a resource called 'product' with the following schema
```
{Schema} = require 'mongoose'
schema: new Schema
	name		: String
	price		: Number
	stock		: Number
```

I can define a couple of aggregate functions called `max-price` and `max-stock`

```
maxPrice = (req, res, next)->
	req.modelQuery = @model
	.aggregate()
	.group _id:null, maxPrice:$max:'$price'
	next()

maxStock = (req, res, next)->
	req.modelQuery = @model
	.aggregate()
	.group _id:null, maxStock: $max:'$stock'
	.select
	next()
```

I then setup the product resource via resourcejs passing in the name and the aggregate functions in the options

product.virtual({name:'max-price', before:maxPrice})
product.virtual({name:'max-stock', before:maxStock})
product.get (etc...)

I can then retrieve the virtual resources using the following urls:

_/product/virtual/max-price_
returns `{_id:null, maxPrice:123}`

_/product/virtual/max-stock_
returns json `{_id:null, maxStock:321}`

I hope that is clear. If this feels like an acceptable approach to you then I will issue a pull request so you can review the code.

Thanks

**Comment by travist** [comment]
I like this approach. Why not define the path of the method during the registration process?

```
product.virtual({path: 'max', name:'max-stock', before:maxStock})
```

This allows you to define the path for the resource... this may seem somewhat redundant with the ```name``` parameter so is there a reason the ```name``` parameter could not be the ```path``` to the virtual resource?

**Comment by biofractal** [comment]
Good idea on re-using the `path` options param. I will make that change.

This will still leave us with the url schema containing the hard-coded url element `virtual`:

_[resource-name]/virtual/[path]_

Are you happy with this?

**Comment by biofractal** [comment]
I have made the changes as requested and we can now use the path options param (see pull request). I think there may be a little more to do as I am not currently checking if the `this.path` value is set and instead only use the `options.path` value. Can you advise please.

**Comment by biofractal** [comment]
merged
