### ISSUE TITLE
Fast JSON patch needs to be updated.

### ISSUE THREAD

**Issue by Sefriol** [travist/resourcejs#120]
Currently if your keys have forward slashes `/` or tildes `~`, replace and remove operations will fail if validation is enabled in `applyPatch`.

https://github.com/Starcounter-Jack/JSON-Patch/pull/268

**Comment by travist** [comment]
We will need to wait for them to submit a new version and then we will pull it in. I do not wish to fork that library.

**Comment by Sefriol** [comment]
I used the PR in my fork for the moment: https://github.com/Sefriol/resourcejs/commit/63d823b7f0ee3ebe5503e2523b55804a6ca752b2
