### ISSUE TITLE
after handlers never invoked from method processing

### ISSUE THREAD

**Issue by biofractal** [travist/resourcejs#2]
The `before` handlers work as expected but the `after` handlers do not. This applies to the generic `after` handler and the method specific `after[method]` handlers.

To replicate this the following options object can be used:

```
options:
	beforeGet:(req, res, next)->
		console.log 'before'
		next()

	afterGet:(req, res, next)->
		console.log 'after'
		next()
```

Calling the the GET route for the applicable resource results in the `before` message being logged but not the `after` message.

Investigations reveal that the `after` function declared in the options is never called, possibly due to the method processing terminating without calling `next()`.

The following method processing does not include a call to `next()` and so does not call the `after` method

```
    /**
     * Register the GET method for this resource.
     */
    get: function(options) {
      this.methods.push('get');
      app.get.apply(app, this.register(this.route + '/:' + this.name + 'Id', function(req, res, next) {
        var query = req.modelQuery || this.model;
        query.findOne({"_id": req.params[this.name + 'Id']}, function(err, item) {
          if (err) return this.respond(res, 500, err);
          if (!item) return this.respond(res, 404);
          res.json(item);
        }.bind(this));
      }, options));
      return this;
    },
```

The same code plus a call to `next()` now successfully calls the `after` function:

```
    /**
     * Register the GET method for this resource.
     */
    get: function(options) {
      this.methods.push('get');
      app.get.apply(app, this.register(this.route + '/:' + this.name + 'Id', function(req, res, next) {
        var query = req.modelQuery || this.model;
        query.findOne({"_id": req.params[this.name + 'Id']}, function(err, item) {
          if (err) return this.respond(res, 500, err);
          if (!item) return this.respond(res, 404);
          res.json(item);
          next() // <-- calling next to invoke the after handler
        }.bind(this));
      }, options));
      return this;
    },
```

I am not sure if calling `next()` here is the appropriate solution however it does highlight the problem.

**Comment by travist** [comment]
This should now be fixed with the latest version update.
