### ISSUE TITLE
Index requests returning 206 without content range specified

### ISSUE THREAD

**Issue by zackurben** [travist/resourcejs#29]
Resource index requests will respond with an HTTP `206` without the user specifying the content-range (not expected and/or normal behavior). To get around this currently, I am adding `?limit=9999` to my queries, where 9999 is some number over my total number of records, thereby forcing the request to return all results and a `200` rather than `206`.

**Comment by dgupta599** [comment]
Confirmed, having the same issue

**Comment by zackurben** [comment]
@dgupta599 yeah, its something with the default pagination number. I think the only thing limiting us from moving forward is, what is a good default?

Right now results are limited internally by default and you can get more with the `limit` param. Maybe its better to revisit the pagination plan use the params to limit the results, otherwise return all of them.

**Comment by dgupta599** [comment]
@zackurben have you found a way to manipulate this default pagination number aside from the ?limit=9999 in the url? I'm looking at possible alternative controller libraries to see if we can bypass these defaults in ResourceJS

**Comment by dgupta599** [comment]
I figured it out. Replace your ./server/controllers/MovieController.js with the following code. Be sure to run `npm install --save node-restful`

```
var restful = require('node-restful');

module.exports = function(app, route) {

  // Setup the controller for REST;

  var rest = restful.model(
  	'approval',
  	app.models.approval
  	).methods(['get','put','post','delete']);

  rest.register(app,'/approval');

  // Return middleware.
  return function(req, res, next) {
    next();
  };
};
```
