### ISSUE TITLE
Override index() query parameters filtering behavior

### ISSUE THREAD

**Issue by HeIsHuaxi** [travist/resourcejs#48]
Index() currently automatically applies filters based on the query parameter that is passed in the request.

Is there a way to override the behavior for a particular query parameter? Say I want to query item?availability=1, instead of filtering items based on availability field on the item object, I want to do something else. 

I tried to do the following in the after handler:

```
if (req.query.availability == 1) {
  console.log("Test Test");
  next();
}
```

It does print the message in the console, but also returns 500 as follows:
```
{
  "status": 500,
  "message": "Cast to ObjectId failed for value \"1\" at path \"availability\"",
  "errors": {}
}
```

Thanks!

**Comment by travist** [comment]
You would need to put this logic within a ```before``` handler, and then add ```req.skipResource = true;``` if you wish to skip this library from handling the response.

**Comment by HeIsHuaxi** [comment]
@travist Thanks! By adding skipResource = true, does it skip filters on all fields? What if I actually want to keep the default behavior for all fields except availability, which I want some customizations?
