### ISSUE TITLE
countQuery.find is not a function

### ISSUE THREAD

**Issue by jmarkinman** [travist/resourcejs#59]
Not sure what I'm doing wrong here...

TypeError: countQuery.find is not a function
Object.\<anonymous> (/../server/node_modules/resourcejs/Resource.js:356:20)

**Comment by prophet60091** [comment]
What triggered the error? I usually see that as a scoping issue, or the dependency injection isn't set up right.

**Comment by jmarkinman** [comment]
>dependency injection

Maybe it's a versioning problem? on most recent version of mongoose, node, everything else, etc.

**Comment by jmarkinman** [comment]
Pretty sure my dependency injection must not be set up right, but still can't pinpoint the fault.
