### ISSUE TITLE
can't get example in README.md to work

### ISSUE THREAD

**Issue by coderofsalvation** [travist/resourcejs#68]
$ npm install resourcejs express mongoose body-parser

And with this app.js:

    var express = require('express');
    var bodyParser = require('body-parser');
    var mongoose = require('mongoose');
    var Resource = require('resourcejs');
    
    // Create the app.
    var app = express();
    
    // Use the body parser.
    app.use(bodyParser.urlencoded({extended: true}));
    app.use(bodyParser.json());
    
    // Create the schema.
    var ResourceSchema = new mongoose.Schema({
      title: {
        type: String,
        required: true
      },
      description: {
        type: String
      },
      count: {
        type: Number
      }
    });
    
    // Create the model.
    var ResourceModel = mongoose.model('Resource', ResourceSchema);
    
    // Create the REST resource.
    Resource(app, '', 'resource', ResourceModel).rest();
    
    app.listen(3000)
    
It runs, but when i do `GET /Resource` nothing happens..it hangs in the browsers, and in curl too:

    $ curl -v -H 'Content-Type: application/json' http://localhost:3000/Resource
    * Hostname was NOT found in DNS cache
    *   Trying ::1...
    * Connected to localhost (::1) port 3000 (#0)
    > GET /Resource HTTP/1.1
    > User-Agent: curl/7.38.0
    > Host: localhost:3000
    > Accept: */*
    > Content-Type: application/json
    > 
    ^C

Installed modules:

    accepts@(unsaved) -> 1.3.3
    array-flatten@(unsaved) -> 1.1.1
    async@(unsaved) -> 2.1.4
    bluebird@(unsaved) -> 2.10.2
    bson@(unsaved) -> 1.0.4
    buffer-shims@(unsaved) -> 1.0.0
    bytes@(unsaved) -> 2.4.0
    composable-middleware@(unsaved) -> 0.3.0
    content-disposition@(unsaved) -> 0.5.1
    content-type@(unsaved) -> 1.0.2
    cookie@(unsaved) -> 0.3.1
    core-util-is@(unsaved) -> 1.0.2
    cookie-signature@(unsaved) -> 1.0.6
    debug@(unsaved) -> 2.2.0
    depd@(unsaved) -> 1.1.0
    ee-first@(unsaved) -> 1.1.1
    destroy@(unsaved) -> 1.0.4
    encodeurl@(unsaved) -> 1.0.1
    es6-promise@(unsaved) -> 3.2.1
    escape-html@(unsaved) -> 1.0.3
    etag@(unsaved) -> 1.7.0
    fast-json-patch@(unsaved) -> 0.5.7
    finalhandler@(unsaved) -> 0.5.0
    fresh@(unsaved) -> 0.3.0
    forwarded@(unsaved) -> 0.1.0
    hooks-fixed@(unsaved) -> 1.2.0
    http-errors@(unsaved) -> 1.5.1
    iconv-lite@(unsaved) -> 0.4.13
    inherits@(unsaved) -> 2.0.3
    ipaddr.js@(unsaved) -> 1.1.1
    isarray@(unsaved) -> 1.0.0
    kareem@(unsaved) -> 1.2.1
    lodash@(unsaved) -> 4.17.4
    media-typer@(unsaved) -> 0.3.0
    merge-descriptors@(unsaved) -> 1.0.1
    methods@(unsaved) -> 1.1.2
    mime@(unsaved) -> 1.3.4
    mime-db@(unsaved) -> 1.25.0
    mime-types@(unsaved) -> 2.1.13
    mongodb@(unsaved) -> 2.2.22
    mongodb-core@(unsaved) -> 2.1.7
    mpath@(unsaved) -> 0.2.1
    mpromise@(unsaved) -> 0.5.5
    mquery@(unsaved) -> 2.2.3
    ms@(unsaved) -> 0.7.1
    muri@(unsaved) -> 1.2.1
    negotiator@(unsaved) -> 0.6.1
    node-paginate-anything@(unsaved) -> 1.0.0
    on-finished@(unsaved) -> 2.3.0
    parseurl@(unsaved) -> 1.3.1
    path-to-regexp@(unsaved) -> 0.1.7
    process-nextick-args@(unsaved) -> 1.0.7
    proxy-addr@(unsaved) -> 1.1.2
    qs@(unsaved) -> 6.2.0
    range-parser@(unsaved) -> 1.2.0
    raw-body@(unsaved) -> 2.1.7
    readable-stream@(unsaved) -> 2.1.5
    regexp-clone@(unsaved) -> 0.0.1
    require_optional@(unsaved) -> 1.0.0
    resolve-from@(unsaved) -> 2.0.0
    semver@(unsaved) -> 5.3.0
    send@(unsaved) -> 0.14.1
    serve-static@(unsaved) -> 1.11.1
    setprototypeof@(unsaved) -> 1.0.2
    sliced@(unsaved) -> 1.0.1
    statuses@(unsaved) -> 1.3.1
    string_decoder@(unsaved) -> 0.10.31
    type-is@(unsaved) -> 1.6.14
    unpipe@(unsaved) -> 1.0.0
    util-deprecate@(unsaved) -> 1.0.2
    utils-merge@(unsaved) -> 1.0.0
    vary@(unsaved) -> 1.1.0

**Comment by coderofsalvation** [comment]
https://github.com/travist/resourcejs/pull/69 <- fix here

**Comment by travist** [comment]
Thanks!
